//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVR_Dash_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FastSwitch {
            get {
                return ((bool)(this["FastSwitch"]));
            }
            set {
                this["FastSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseOculusServicesOnExit {
            get {
                return ((bool)(this["CloseOculusServicesOnExit"]));
            }
            set {
                this["CloseOculusServicesOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RunOculusClientOnStartup {
            get {
                return ((bool)(this["RunOculusClientOnStartup"]));
            }
            set {
                this["RunOculusClientOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SteamVRFocusFix {
            get {
                return ((bool)(this["SteamVRFocusFix"]));
            }
            set {
                this["SteamVRFocusFix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExitLinkOn_UserExit_SteamVR {
            get {
                return ((bool)(this["ExitLinkOn_UserExit_SteamVR"]));
            }
            set {
                this["ExitLinkOn_UserExit_SteamVR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseOculusClientOnExit {
            get {
                return ((bool)(this["CloseOculusClientOnExit"]));
            }
            set {
                this["CloseOculusClientOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Minimize_Oculus_Client_OnClientStart {
            get {
                return ((bool)(this["Minimize_Oculus_Client_OnClientStart"]));
            }
            set {
                this["Minimize_Oculus_Client_OnClientStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Hover_Activation_Time {
            get {
                return ((int)(this["Hover_Activation_Time"]));
            }
            set {
                this["Hover_Activation_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ignore_SteamVR_Status_HoverButtonAction {
            get {
                return ((bool)(this["Ignore_SteamVR_Status_HoverButtonAction"]));
            }
            set {
                this["Ignore_SteamVR_Status_HoverButtonAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuestPolling {
            get {
                return ((bool)(this["QuestPolling"]));
            }
            set {
                this["QuestPolling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Automatic_Audio_Switching {
            get {
                return ((bool)(this["Automatic_Audio_Switching"]));
            }
            set {
                this["Automatic_Audio_Switching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Normal_Speaker_ID {
            get {
                return ((int)(this["Normal_Speaker_ID"]));
            }
            set {
                this["Normal_Speaker_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Quest_Speaker_ID {
            get {
                return ((int)(this["Quest_Speaker_ID"]));
            }
            set {
                this["Quest_Speaker_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid Normal_Speaker_GUID {
            get {
                return ((global::System.Guid)(this["Normal_Speaker_GUID"]));
            }
            set {
                this["Normal_Speaker_GUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid Quest_Speaker_GUID {
            get {
                return ((global::System.Guid)(this["Quest_Speaker_GUID"]));
            }
            set {
                this["Quest_Speaker_GUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Auto_Audio_Change_DefaultCommunication {
            get {
                return ((bool)(this["Auto_Audio_Change_DefaultCommunication"]));
            }
            set {
                this["Auto_Audio_Change_DefaultCommunication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[]")]
        public string Auto_Programs_JSON {
            get {
                return ((string)(this["Auto_Programs_JSON"]));
            }
            set {
                this["Auto_Programs_JSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid Normal_Microphone_GUID {
            get {
                return ((global::System.Guid)(this["Normal_Microphone_GUID"]));
            }
            set {
                this["Normal_Microphone_GUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid Quest_Microphone_GUID {
            get {
                return ((global::System.Guid)(this["Quest_Microphone_GUID"]));
            }
            set {
                this["Quest_Microphone_GUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Automatic_Microphone_Switching {
            get {
                return ((bool)(this["Automatic_Microphone_Switching"]));
            }
            set {
                this["Automatic_Microphone_Switching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Auto_Microphone_Change_DefaultCommunication {
            get {
                return ((bool)(this["Auto_Microphone_Change_DefaultCommunication"]));
            }
            set {
                this["Auto_Microphone_Change_DefaultCommunication"] = value;
            }
        }
    }
}
